<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="BM1MC97Y2" ignored="0" name="Sanity Test" tests="5" failures="1" timestamp="26 Oct 2020 10:11:37 GMT" time="21.479" errors="0">
  <testcase name="verifyLoginPageTitle" time="8.96" classname="com.hubspotapp.test.LoginPageTest"/>
  <testcase name="verifySignUpLinkIsDisplayed" time="0.067" classname="com.hubspotapp.test.LoginPageTest"/>
  <testcase name="verifySignUpLinkTextIsDisplayed" time="0.068" classname="com.hubspotapp.test.LoginPageTest"/>
  <testcase name="verifyForgotPasswordLinkIsDisplayed" time="0.036" classname="com.hubspotapp.test.LoginPageTest"/>
  <testcase name="verifyLogin" time="0.404" classname="com.hubspotapp.test.LoginPageTest">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.hubspotapp.util.ElementActions.doClick(ElementActions.java:38)
at com.hubspotapp.pages.HomePage.clickOnAccountMenu(HomePage.java:38)
at com.hubspotapp.pages.HomePage.getAccountName(HomePage.java:42)
at com.hubspotapp.test.LoginPageTest.verifyLogin(LoginPageTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
    </failure>
  </testcase> <!-- verifyLogin -->
</testsuite> <!-- Sanity Test -->
